# Generated by Django 3.2 on 2024-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True,
                                                    verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True,
                                                    verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100,
                                           verbose_name='Название управления')),
            ],
            options={
                'verbose_name': 'Управления',
                'verbose_name_plural': 'Управление',
                'db_table': 'administration',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True,
                                                    verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True,
                                                    verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100,
                                           verbose_name='Название отдела')),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='departments',
                                                     to='api.administration',
                                                     verbose_name='Управление')),
            ],
            options={
                'verbose_name': 'Отделы',
                'verbose_name_plural': 'Отдел',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False,
                                        unique=True,
                                        verbose_name='Уникальный идентификатор подразделения.')),
                ('source', models.CharField(choices=[('SERVICE', 'Служба'),
                                                     ('ADMINISTRATION', 'Управления'),
                                                     ('DEPARTMENT', 'Отдел'),
                                                     ('GROUP', 'Группа')],
                                            max_length=15,
                                            verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Подразделения',
                'verbose_name_plural': 'Подразделение',
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='employee',
                                            verbose_name='Фото пользователя.')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудник',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True,
                                                    verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True,
                                                    verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, unique=True,
                                           verbose_name='Название службы')),
                ('division', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                  to='api.division')),
            ],
            options={
                'verbose_name': 'Службы',
                'verbose_name_plural': 'Служба',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True,
                                                    verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True,
                                                    verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, verbose_name='Название группы')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='groups', to='api.department',
                                                 verbose_name='Отдел')),
                ('division', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                  to='api.division')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группа',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('start_at', models.DateField(verbose_name='Дата начала работы')),
                ('end_at', models.DateField(blank=True, null=True,
                                            verbose_name='Дата окончания работы')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='api.division', verbose_name='Подразделение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='api.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Личный состав подразделения.',
                'verbose_name_plural': 'Подразделение сотрудника.',
                'db_table': 'employee_x_division',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ManyToManyField(related_name='employees', through='api.EmployeeDivision',
                                         to='api.Division', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='api.division'),
        ),
        migrations.AddField(
            model_name='administration',
            name='division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='api.division'),
        ),
        migrations.AddField(
            model_name='administration',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='administrations', to='api.service',
                                    verbose_name='Служба'),
        ),
    ]
